# Site settings
title: Subnero
description: The future of underwater wireless.
url: "http://subnero1.github.io/"
twitter_username: subnero
github_username:  subnero1
default_image: images/pulse-thumbnail-default.jpg

# Build settings
markdown: kramdown
encoding:    UTF-8
highlighter: rouge

# Google Analytics
google_analytics: UAâ€”130948711-1
