# Site settings
title: Subnero
description: > # this means to ignore newlines until "baseurl:"
  The future of underwater wireless.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://subnero1.github.io/" # the base hostname & protocol for your site
twitter_username: subnero
github_username:  subnero1
default_image: images/pulse-thumbnail-default.jpg

# Build settings
markdown: kramdown
encoding:    UTF-8
highlighter: rouge

# Google Analytics
google_analytics: UAâ€”130948711-1
