# Site settings
title: Subnero
description: The future of underwater wireless.
url: "https://subnero.com"
twitter_username: subnero
github_username:  subnero1
default_image: images/pulse-thumbnail-default.jpg

collections:
  faq:
    output: false
  gen4x:
    output: true
    permalink: /products/gen4x/:title/
  userstories: 
    output: true
    permalink: /user-stories/:title/

# Build settings
markdown: kramdown
encoding:    UTF-8
highlighter: rouge
exclude: ["readme.md", "**/readme.md", "README.md", "**/README.md"]

# Google Analytics
google_analytics: UAâ€”130948711-1
